version: '3.7'

services:
  app:
    restart: unless-stopped
    build: ./beautiful_weather
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./beautiful_weather:/beautiful_weather
    command: python manage.py runserver 0.0.0.0:8000
